export const styles = {
  "align-items-center": ["alignItems", "center"],
  "align-items-end": ["alignItems", "flex-end"],
  "align-items-start": ["alignItems", "flex-start"],
  "align-items-stretch": ["alignItems", "stretch"],
  "background-blue": ["backgroundColor", "rgba(0, 0, 255, 0.5)"],
  "background-gradient": ["background", "linear-gradient(to right, #ff7e5f, #feb47b)"],
  "background-green": ["backgroundColor", "rgba(0, 255, 0, 0.5)"],
  "background-red": ["backgroundColor", "rgba(255, 0, 0, 0.5)"],
  "background-transparent": ["backgroundColor", "transparent"],
  "background-yellow": ["backgroundColor", "rgba(255, 255, 0, 0.5)"],
  "border-color": ["borderColor", "black"],
  "border-dashed-red": ["border", "2px dashed red"],
  "border-radius": ["borderRadius", "10px"],
  "border-radius-full": ["borderRadius", "50%"],
  "border-radius-small": ["borderRadius", "5px"],
  "border-solid-black": ["border", "2px solid black"],
  "border-width": ["borderWidth", "1px"],
  "bottom-0": ["bottom", "0"],
  "box-shadow": ["boxShadow", "0 4px 8px rgba(0, 0, 0, 0.2)"],
  "cursor-default": ["cursor", "default"],
  "cursor-not-allowed": ["cursor", "not-allowed"],
  "cursor-pointer": ["cursor", "pointer"],
  "display-block": ["display", "block"],
  "display-flex": ["display", "flex"],
  "display-inline-block": ["display", "inline-block"],
  "display-none": ["display", "none"],
  "filter-blur": ["filter", "blur(5px)"],
  "filter-grayscale": ["filter", "grayscale(100%)"],
  "flex-basis": ["flexBasis", "auto"],
  "flex-direction-column": ["flexDirection", "column"],
  "flex-direction-row": ["flexDirection", "row"],
  "flex-grow": ["flexGrow", "1"],
  "flex-shrink": ["flexShrink", "1"],
  "font-feature-settings-normal": ["fontFeatureSettings", "normal"],
  "font-kerning-normal": ["fontKerning", "normal"],
  "font-language-override-normal": ["fontLanguageOverride", "normal"],
  "font-optical-sizing-auto": ["fontOpticalSizing", "auto"],
  "font-optical-sizing-none": ["fontOpticalSizing", "none"],
  "font-palette-custom": ["fontPalette", "custom"],
  "font-palette-dark": ["fontPalette", "dark"],
  "font-palette-inherit": ["fontPalette", "inherit"],
  "font-palette-initial": ["fontPalette", "initial"],
  "font-palette-light": ["fontPalette", "light"],
  "font-palette-normal": ["fontPalette", "normal"],
  "font-palette-revert": ["fontPalette", "revert"],
  "font-palette-revert-layer": ["fontPalette", "revert-layer"],
  "font-palette-unset": ["fontPalette", "unset"],
  "font-size-large": ["fontSize", "24px"],
  "font-size-medium": ["fontSize", "18px"],
  "font-size-small": ["fontSize", "14px"],
  "font-stretch-condensed": ["fontStretch", "condensed"],
  "font-stretch-expanded": ["fontStretch", "expanded"],
  "font-style-italic": ["fontStyle", "italic"],
  "font-style-oblique": ["fontStyle", "oblique"],
  "font-synthesis-small-caps": ["fontSynthesis", "small-caps"],
  "font-synthesis-style": ["fontSynthesis", "style"],
  "font-synthesis-weight": ["fontSynthesis", "weight"],
  "font-variant-small-caps": ["fontVariant", "small-caps"],
  "font-variation-settings-normal": ["fontVariationSettings", "normal"],
  "font-weight-bold": ["fontWeight", "bold"],
  "font-weight-normal": ["fontWeight", "normal"],
  "height-full": ["height", "100%"],
  "justify-content-around": ["justifyContent", "space-around"],
  "justify-content-between": ["justifyContent", "space-between"],
  "justify-content-center": ["justifyContent", "center"],
  "justify-content-end": ["justifyContent", "flex-end"],
  "justify-content-start": ["justifyContent", "flex-start"],
  "letter-spacing-wide": ["letterSpacing", "2px"],
  "line-height-1-5": ["lineHeight", "1.5"],
  "list-style-none": ["listStyle", "none"],
  "margin-10": ["margin", "10px"],
  "margin-20": ["margin", "20px"],
  "margin-auto": ["margin", "0 auto"],
  "max-width": ["maxWidth", "100%"],
  "min-height": ["minHeight", "50px"],
  "opacity-50": ["opacity", "0.5"],
  "opacity-75": ["opacity", "0.75"],
  "outline-none": ["outline", "none"],
  "overflow-auto": ["overflow", "auto"],
  "overflow-hidden": ["overflow", "hidden"],
  "overflow-scroll": ["overflow", "scroll"],
  "overflow-wrap-break-word": ["overflowWrap", "break-word"],
  "padding-10": ["padding", "10px"],
  "padding-20": ["padding", "20px"],
  "padding-bottom-10": ["paddingBottom", "10px"],
  "padding-top-10": ["paddingTop", "10px"],
  "pointer-events-none": ["pointerEvents", "none"],
  "position-absolute": ["position", "absolute"],
  "position-fixed": ["position", "fixed"],
  "position-relative": ["position", "relative"],
  "resize-none": ["resize", "none"],
  "right-0": ["right", "0"],
  "table-layout-fixed": ["tableLayout", "fixed"],
  "text-align-center": ["textAlign", "center"],
  "text-align-left": ["textAlign", "left"],
  "text-align-right": ["textAlign", "right"],
  "text-black": ["color", "black"],
  "text-blue": ["color", "blue"],
  "text-decoration-blink": ["textDecoration", "blink"],
  "text-decoration-line-through": ["textDecoration", "line-through"],
  "text-decoration-overline": ["textDecoration", "overline"],
  "text-decoration-underline": ["textDecoration", "underline"],
  "text-green": ["color", "green"],
  "text-red": ["color", "red"],
  "text-transform-uppercase": ["textTransform", "uppercase"],
  "text-white": ["color", "white"],
  "top-0": ["top", "0"],
  "transform-rotate": ["transform", "rotate(15deg)"],
  "transform-scale": ["transform", "scale(1.1)"],
  "transition-all": ["transition", "all 0.3s ease"],
  "user-select-none": ["userSelect", "none"],
  "vertical-align-middle": ["verticalAlign", "middle"],
  "visibility-hidden": ["visibility", "hidden"],
  "visibility-visible": ["visibility", "visible"],
  "white-space-nowrap": ["whiteSpace", "nowrap"],
  "width-full": ["width", "100%"],
  "word-break-normal": ["wordBreak", "normal"],
  "z-index-10": ["zIndex", "10"],
  "z-index-100": ["zIndex", "100"],
};